### ISSUE TITLE
track o matic error upon login

### ISSUE THREAD

**Issue by spmartin13** [joev/SVUI-Temp#1]
soon as I log In with my 110, I get this message greeting me:

Message: ...e\AddOns\SVUI_TrackOMatic\components\triangulate.lua:166: attempt to compare number with nil
Time: 09/17/16 22:42:53
Count: 1
Stack: ...e\AddOns\SVUI_TrackOMatic\components\triangulate.lua:166: in function `SetTempData'
...e\AddOns\SVUI_TrackOMatic\components\triangulate.lua:191: in main chunk

Locals: map = <table> {
 0 = <table> {
 }
 mapName = "Kalimdor"
 cont = 1
 zone = 0
}
mapName = "Kalimdor"
id = 13
numFloors = nil
_ = 0
TLx = 17066.599609375
TLy = 12799.900390625
BRx = -19733.19921875
BRy = -11733.299804688
(_temporary) = <table> {
 BRy = -11733.299804688
 BRx = -19733.19921875
 TLy = 12799.900390625
 TLx = 17066.599609375
}
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(*temporary) = "attempt to compare number with nil"
GetMapInfo = <function> defined =[C]:-1
GetCurrentMapAreaID = <function> defined =[C]:-1
GetNumDungeonMapLevels = <function> defined =[C]:-1
GetCurrentMapContinent = <function> defined =[C]:-1
GetCurrentMapZone = <function> defined =[C]:-1
GetCurrentMapDungeonLevel = <function> defined =[C]:-1
SetDungeonMapLevel = <function> defined =[C]:-1
temp_cache = <table> {
}

**Comment by drveoj** [comment]
Hi @spmartin13 

I believe I've fixed this. If you go to the code tab, Click on "Clone or Download" and download the Zip and install as normal thereafter and let me know how you get on :) 

Won't close the issue until you respond. 

Regards
joev

**Comment by spmartin13** [comment]
it does not appear when I log in now, however it still shows up when I mouse over the garrison docket area.  i will consider it good.  thanks.

**Comment by drveoj** [comment]
Sorry: You get the same error (about triangulate.lua) or another? Could you post the error please? I thought I'd sorted out all the garrison docklet errors (but clearly not). 

Thanks

joev

**Comment by spmartin13** [comment]
this is the docket error i get when i mouse over it:

Message: ...face\AddOns\SVUI_!Core\system_docklets\garrison.lua:152: Usage: GetInProgressMissions([missionList,] garrFollowerTypeID)
Time: 09/18/16 19:35:17
Count: 1
Stack: [C]: in function `GetInProgressMissions'
...face\AddOns\SVUI_!Core\system\_docklets\garrison.lua:152: in function <...face\AddOns\SVUI_!Core\system\_docklets\garrison.lua:145>
...face\AddOns\SVUI_!Core\system\_docklets\garrison.lua:240: in function`GeneralTip'
Interface\AddOns\SVUI_!Core\system\dock.lua:1260: in function <Interface\AddOns\SVUI_!Core\system\dock.lua:1251>

Locals: (*temporary) = <table> {
}

thanks.

**Comment by spmartin13** [comment]
The socket err has been posted. Thanks.

**Comment by spmartin13** [comment]
has been fixed.  thanks.

**Comment by drveoj** [comment]
Was about to write: Think I've fixed that, please re-download but you've found that out already :)
