### ISSUE TITLE
Micro menu bar / Action Bars

### ISSUE THREAD

**Issue by silenced24** [joev/SVUI-Temp#50]
I am sorry I don't have a screenshot but the skinning for the Micro menu Bar ( buttons for your character window, spell book, talents, mounts, etc... ) Is messed up. Like, on two of the buttons it's like it's showing the default ui behind the skinned ui. 

And is there a way to implement separate keybinds per specialization? So, when I switch from Ret to Holy I can set spec specific actionbar keybinds?

**Comment by drveoj** [comment]
Regarding first point: I've seen this on the Game Menu button so can confirm it's a bug. I'll look into it. 

Regarding the second: The game engine already caters for this by swapping your action bars when your spec changes... I'm not sure the benefit of doing keybind remaps.. surely you'd always want to press (for example) the 1 key to activate actionbar button 1 etc.?

**Comment by silenced24** [comment]
Yeah it's no big deal. It's just a matter of putting spells where the key
bind is. Just an OCD thing I guess :p Another issue I've noticed is
randomly the player unit frame will disappear. Everything else stays and is
fine but just the player unit frame. You can /reload to bring it back.

**Comment by drveoj** [comment]
Currently the bug around the wrong icons behind the micro bar icons only shows on the Main Menu one for me (which I've now fixed and will push the changes for later with some more fixes). Is there another misbehaving? 

Regarding the unitframe issue: Not seen that one ever. Can you see if you can figure out what causes it (i.e. what activities you're up to) and post me a separate issue on it (ideally with reproduction info) 

Many thanks

joev

**Comment by silenced24** [comment]
Installed updated SVUI and I am still getting the micro menu bar bug with
the "guild" icon. The default ui is showing up behind the skinned ui.

**Comment by drveoj** [comment]
@silenced24 Is that on a character with or without guild (or both?) 

Is it on a character where the guild has a tabard or not? 

Think I know what's causing it, just need to confirm. 

regards

joev

**Comment by silenced24** [comment]
With guild and with tabard.
